### ISSUE TITLE
Set up Release Drafter action and vet workflow

### ISSUE THREAD

**Issue by mshick** [takeshape/.github#10]
**Description**
We would like to start automating our releases so we can better update the general public on the product.

**Additional context**
[Release Drafter](https://github.com/marketplace/actions/release-drafter) is a very popular GitHub Action that does this. Let's try it out.

**Tasks**

- [x] Add Release Drafter to a repo.
- [x] Create a couple PRs
- [x] Run through a typical release cycle
- [ ] Document a recommended approach (note BREAKING CHANGE workflow) [in notion](https://www.notion.so/takeshapeio/Release-takeshape-87a24610a10a4384abe04c5357118372)
- [ ] Method to increment versions in package.json and other files?

**Related Issues**

- [in notion](https://www.notion.so/takeshapeio/Automate-changelog-release-based-on-our-GitHub-releases-94f7c4f4ec584d50962e13a2c9b3dc10)

**Followers**
@allanlasser @asprouse @mcat

**Comment by asprouse** [comment]
The drafter does a great job at automating the release notes step (see [step 2.1](https://www.notion.so/takeshapeio/Release-takeshape-87a24610a10a4384abe04c5357118372#df9c4596b83942a4bb9f3ab87319e5bd)) in our release process.

The [version bump commit](https://www.notion.so/takeshapeio/Release-takeshape-87a24610a10a4384abe04c5357118372#7a216d135cbc4c82bd0105809f540431) in the release workflow is pushed before publishing the release (creates a tag with the same name). This is done first so that CI will include the correct version number in the modules deployed to AWS (client, api) and is obviously needed before publishing to NPM.

Does the drafter simply ignore the bump commit and it's up to the user doing a release to ensure they select it from the commit dropdown? Or are there automated ways that this is typically set up?
