### ISSUE TITLE
Add status labels for Codetree

### ISSUE THREAD

**Issue by mcat** [takeshape/.github#27]
## Tasks

- [x] Add "stage: backlog"
- [x] Add "stage: in progress"
- [x] Add "stage: waiting on review"
- [x] Add "stage: in review"
